[package]
name = "gitflow-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
colored = "3.0.0"
git2 = "0.20.0"
log = "0.4.26"
thiserror = "2.0.11"
